import type { MeetingAnalysis } from "@/types/analysis"

export function toMarkdown(analysis: MeetingAnalysis): string {
  const { title, summary, actionItems, decisions, participants } = analysis

  const items = actionItems
    .map((a) => `- [ ] **${a.task}** — ${a.assignee} | Due: ${a.due} | Priority: ${a.priority}`)
    .join("\n")

  const dec = decisions.map((d) => `- ${d}`).join("\n")

  const people = participants.map((p) => `- ${p.name} (${p.role})`).join("\n")

  return `# ${title}

## Summary
${summary}

## Action Items
${items || "None"}

## Key Decisions
${dec || "None"}

## Participants
${people || "None"}

---
*Generated by Minutely*
`
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}

export function downloadMarkdown(analysis: MeetingAnalysis): void {
  const md = toMarkdown(analysis)
  const blob = new Blob([md], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${analysis.title.replace(/\s+/g, "-").toLowerCase()}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function toNotionClipboard(analysis: MeetingAnalysis): string {
  return toMarkdown(analysis)
}